version: "3.8"
services:
  service_postgres:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: secret
      POSTGRESS_USER: root
      POSTGRESS_DB: employees
    ports:
    -5432 : 5432
  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    environment:
    PGADMIN_DEFAULT_EMAIL: sulderyarellano@dev.com
    PGADMIN_DEFAULT_PASSWORD: secret
  ports: 
  -8080:80
  depends_on:
  -service_postgres
